version: '2.1'
services:
    postgres_db:
        image: postgres:latest
        env_file:
               - airflow_env
        ports:
               - "5433:5432"
        restart: always
        volumes:
                - /home/igf/postgres_airflow_db:/var/lib/postgresql/data:z
        container_name: airflow_db
        networks:
               - default
    postgres_results_db:
        image: postgres:latest
        env_file:
               - airflow_env
        ports:
               - "5434:5432"
        restart: always
        volumes:
                - /home/igf/postgres_airflow_results_db:/var/lib/postgresql/data:z
        container_name: airflow_results_db
        networks:
               - default
    redis:
        image: redis:latest
        ports:
              - "6379:6379"
        restart: always
        volumes:
               - /home/igf/redis_conf/redis.conf:/usr/local/etc/redis/redis.conf:z
               - /home/igf/redis_airflow_data:/data:z
        container_name: redis-server
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        networks:
               - default
    webserver:
        image: apache/airflow:1.10.12
        env_file:
                - airflow_env
        links:
                - airflow_db
                - airflow_results_db
                - redis-server
        ports:
                - "8083:8080"
        volumes:
                - /home/igf/airflow/logs:/opt/airflow/logs:z
                - /home/igf/github/igf-airflow-scripts/airflow-dags:/opt/airflow/dags:z
                - /home/igf/ssl_cert/airflow.cert:/SSL/airflow.cert:z \
                - /home/igf/ssl_cert/airflow.key:/SSL/airflow.key:z \
        depends_on:
                - airflow_db
                - airflow_results_db
                - redis-server
        restart: always
        command: webserver
        container_name: airflow-webserver
        networks:
               - default
    scheduler:
        image: apache/airflow:1.10.12
        env_file:
                - airflow_env
        links:
                - airflow_db
                - airflow_results_db
                - redis-server
        depends_on:
                - airflow_db
                - airflow_results_db
                - airflow-webserver
                - redis-server
        volumes:
                - /home/igf/airflow/logs:/opt/airflow/logs:z
                - /home/igf/github/igf-airflow-scripts/airflow-dags:/opt/airflow/dags:z
        restart: always
        command: scheduler
        container_name: airflow-scheduler
        networks:
               - default
    airflow-worker:
        image: apache/airflow:1.10.12
        env_file:
                - airflow_env
        links:
                - airflow_db
                - airflow_results_db
                - redis-server
        depends_on:
                - airflow_db
                - airflow_results_db
                - airflow-webserver
                - redis-server
                - airflow-scheduler
        volumes:
                - /home/igf/airflow/logs:/opt/airflow/logs:z
                - /home/igf/github/igf-airflow-scripts/airflow-dags:/opt/airflow/dags:z
        restart: always
        command: worker
        container_name: airflow-worker1
        networks:
               - default
    adminer:
        image: adminer:latest
        ports:
                - "8081:8080"
        depends_on:
                - airflow_db
                - airflow_results_db
        links:
                - airflow_db
                - airflow_results_db
        restart: always
        container_name: adminer
        networks:
               - default
